[build]
  command = "npm --prefix frontend install && npm --prefix frontend run build"
  publish = "frontend/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
